# Default values for back-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: chxmxii/backend
  pullPolicy: IfNotPresent
  tag: "latest"

nameOverride: "backend"
fullnameOverride: "backend"

serviceAccount:
  create: true
  automount: false
  name: "backend-sa"

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /healtz
    port: http-back

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

environment:
  - name: DB_HOST
    value: "mysql"
  - name: DB_USER
    value: "root"
  - name: DB_PASSWORD
    value: "notsosecure"  
  - name: DB_NAME
    value: "testdb"