replicaCount: 1

image:
  repository: chxmxii/frontend
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: "frontend"
fullnameOverride: "frontend"

serviceAccount:
  create: true
  automount: false
  name: "front-sa"

service:
  type: ClusterIP
  port: 8081

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: devops-chall.chxmxii.me
      paths:
        - path: /
          pathType: Prefix
  tls:
   - secretName: chall-tls
     hosts:
       - devops-chall.chxmxii.me

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80